swagger: '2.0'
info:
  title: Bowling REST-API
  description: REST API for Bowling game
  version: '1'
host: api.antonu.org
basePath: /bowling/v1
schemes:
  - http
  - https
paths:
  /games:
    get:
      summary: Returns list of games
      produces:
        - application/json
      responses:
        '200':
          description: OK
    post:
      summary: Create new game
      produces:
        - application/json
      responses:
        '201':
          description: Created
  '/game/{id}':
    get:
      summary: Gets a game information by ID
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Game ID
          type: string
          required: true
      responses:
        '200':
          description: A Game object
          schema:
            $ref: '#/definitions/Game'
    put:
      summary: Make a toss
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: Game ID
          type: string
          required: true
      responses:
        '200':
          description: A Game object
          schema:
            $ref: '#/definitions/Game'
        '405':
          description: Game is finished
          schema:
            $ref: '#/definitions/Game'
definitions:
  Game:
    type: object
    properties:
      id:
        type: string
        description: Game ID
      finished:
        type: boolean
        description: Game is finished flag
      totalScore:
        type: integer
        description: Game total score
      rounds:
        type: array
        items:
          $ref: '#/definitions/Round'
    required:
      - id
      - finished
      - totalScore
      - rounds
  Round:
    type: object
    properties:
      balls:
        type: array
        items:
          type: integer
      score:
        type: integer
        description: Game score round
    required:
      - balls
      - score
