---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-alpine'

inputs:
- name: source-code
- name: version

outputs:
- name: artifacts

run:
  path: ci/scripts/build-artifact.sh
  dir: source-code
