---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pull-request
  type: pull-request
  source:
    repo: ((github_repo))
    private_key: ((private_key))
    access_token: ((github_token))

- name: draft-version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: ((github_repo_uri))
    branch: version
    file: version_draft
    private_key: ((private_key))

jobs:
- name: build-pr
  plan:
  - get: pull-request
    trigger: true
    version: every

  - put: pull-request
    params:
      path: pull-request
      context: unit-tests
      status: pending

  - task: unit-tests
    input_mapping: { source-code: pull-request }
    file: pull-request/ci/tasks/unit-tests.yml
    on_success:
      put: pull-request
      params:
        path: pull-request
        context: unit-tests
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        context: unit-tests
        status: failure

- name: create-draft-release
  plan:
  - get: draft-version
    pre: draft

  - get: pull-request
    passed:
    - build-pr

  - task: build-artifact
    input_mapping: 
      source-code: pull-request
      version: draft-version
    file: pull-request/ci/tasks/build-artifact.yml
    params:
      VERSION_FILE: version_draft
