---
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: pull-request
  type: pull-request
  source:
    repo: "((github_repo))"
    private_key: ((private_key))
    access_token: ((github_token))

jobs:
- name: build-pr
  plan:
  - get: source-code
    resource: pull-request
    trigger: true
    version: every

  - put: source-code
    resource: pull-request
    params:
      path: source-code
      context: unit-tests
      status: pending

  - task: unit-tests
    file: source-code/ci/tasks/unit-tests.yml
    on_success:
      put: source-code
      resource: pull-request
      params:
        path: source-code
        context: unit-tests
        status: success
    on_failure:
      put: source-code
      resource: pull-request
      params:
        path: source-code
        context: unit-tests
        status: failure
