---

#-----------------------------------------------------------------------------------------------------------------------
# Resource Types
#-----------------------------------------------------------------------------------------------------------------------
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

#-----------------------------------------------------------------------------------------------------------------------
# Resources
#-----------------------------------------------------------------------------------------------------------------------
resources:
- name: pull-request
  type: pull-request
  source:
    repo: ((github_repo))
    private_key: ((private_key))
    access_token: ((github_token))

- name: git-master
  type: git
  source:
    uri: ((github_repo_uri))
    branch: master
    private_key: ((private_key))

- name: draft-version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: ((github_repo_uri))
    branch: version
    file: version_draft
    private_key: ((private_key))

- name: release-version
  type: semver
  source:
    initial_version: 0.0.1
    driver: git
    uri: ((github_repo_uri))
    branch: version
    file: version
    private_key: ((private_key))

- name: gh-release-draft
  type: github-release
  source:
    owner: antonu17
    repository: bowling-game
    access_token: ((github_token))
    drafts: true

- name: gh-release-candidate
  type: github-release
  source:
      user: antonu17
      repository: bowling-game
      access_token: ((github_token))
      pre_release: true
      release: false
      drafts: false

- name: gh-release-final
  type: github-release
  source:
      user: antonu17
      repository: bowling-game
      access_token: ((github_token))
      pre_release: false
      release: true
      drafts: false

#-----------------------------------------------------------------------------------------------------------------------
# Groups
#-----------------------------------------------------------------------------------------------------------------------
groups:
- name: Overall
  jobs:
  - build-pr
  - build-release-candidate
  - promote-a-release
  - deploy-app-staging
  - deploy-app-live

- name: PR
  jobs:
  - build-pr

- name: Master
  jobs:
  - build-release-candidate
  - promote-a-release
  - deploy-app-staging
  - deploy-app-live

#-----------------------------------------------------------------------------------------------------------------------
# Jobs
#-----------------------------------------------------------------------------------------------------------------------
jobs:

#-----------------------------------------------------------------------------------------------------------------------
# Pull Request flow
#-----------------------------------------------------------------------------------------------------------------------
- name: build-pr
  serial_groups:
  - draft-version

  plan:
  - get: pull-request
    trigger: true
    version: every

  - put: pull-request
    params:
      path: pull-request
      context: unit-tests
      status: pending

  - get: draft-version
    params:
      pre: draft

  - task: unit-tests
    input_mapping:
      source-code: pull-request
    file: pull-request/ci/tasks/unit-tests.yml
    on_success:
      put: pull-request
      params:
        path: pull-request
        context: unit-tests
        status: success
    on_failure:
      put: pull-request
      params:
        path: pull-request
        context: unit-tests
        status: failure

  - task: build-artifact
    input_mapping: 
      source-code: pull-request
      version: draft-version
    file: pull-request/ci/tasks/build-artifact.yml

  - task: create-draft
    input_mapping:
      source-code: pull-request
    file: pull-request/ci/tasks/create-draft.yml

  - put: gh-release-draft
    params:
      name: draft-version/version
      tag: draft/tag
      body: draft/body
      globs:
      - artifacts/*

  - put: draft-version
    params:
      file: draft-version/version

#-----------------------------------------------------------------------------------------------------------------------
# Master flow
#-----------------------------------------------------------------------------------------------------------------------
- name: build-release-candidate
  plan:
  - get: git-master
    trigger: true

  - get: release-version
    params:
      bump: patch
      pre: rc

  - task: unit-tests
    input_mapping:
      source-code: git-master
    file: git-master/ci/tasks/unit-tests.yml

  - task: build-artifact
    input_mapping:
      source-code: git-master
      version: release-version
    file: git-master/ci/tasks/build-artifact.yml

  - put: gh-release-candidate
    params:
      name: release-version/version
      tag: release-version/version
      globs:
      - artifacts/*

  - put: release-version
    params:
      file: release-version/version

- name: promote-a-release
  plan:
  - get: gh-release-candidate

  - get: release-version
    params:
      bump: final

  - put: gh-release-final
    params:
        name: release-version/version
        tag:  release-version/version
        globs:
            - gh-release-candidate/*.tar.gz

  - put: release-version
    params:
      bump: patch
      pre: rc

- name: deploy-app-staging
- name: deploy-app-live
